export const metadata = {
  title: 'Концерты',
  description: 'Generated by create next app',
};

export default function ConcertsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div className='div'>{children}</div>;
}
