import Link from 'next/link';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <>
          <Link href='/'>Главная</Link>
          <Link href='/concerts'>Концерты</Link>
          <Link href='/users'>Юзеры</Link>
          {children}
        </>
      </body>
    </html>
  );
}
