export const metadata = {
  title: '2024',
  description: 'Generated by create next app',
};

export default function ConcertsLayout2024({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div className='div2024'>1231312321312{children}</div>;
}
